#!/usr/bin/env bash
# ig-term :: modules/shell/configure.sh

source "${IG_HOME}/core/log.sh"
source "${IG_HOME}/core/config.sh"
source "${IG_HOME}/core/symlink.sh"
source "${IG_HOME}/core/state.sh"
source "${IG_HOME}/core/logger.sh"

_configure_shell() {
  local mod_dir="${IG_HOME}/modules/shell"

  # .zshenv -> symlink to our file in modules
  ig_link "${mod_dir}/zsh/zshenv.zsh" "${HOME}/.zshenv"
  ig_state_config_track "shell" "${mod_dir}/zsh/zshenv.zsh" "${HOME}/.zshenv"

  # .zshrc -> symlink to our file in modules
  ig_link "${mod_dir}/zsh/zshrc.zsh" "${HOME}/.zshrc"
  ig_state_config_track "shell" "${mod_dir}/zsh/zshrc.zsh" "${HOME}/.zshrc"

  # .zimrc -> symlink to our file in modules
  local zim_dir="${IG_CONFIG_DIR}/zim"
  mkdir -p "$zim_dir"
  ig_link "${mod_dir}/zsh/zimrc.zsh" "${zim_dir}/.zimrc"
  ig_state_config_track "shell" "${mod_dir}/zsh/zimrc.zsh" "${zim_dir}/.zimrc"

  # Generate FZF color opts from theme into IG_HOME/config/shell/
  local fzf_colors="pointer:${IG_COLOR_FG:-#a9b1d6}"
  fzf_colors+=",bg+:${IG_COLOR_SELECTION_BG:-#28344a}"
  fzf_colors+=",fg:${IG_COLOR_FG:-#a9b1d6}"
  fzf_colors+=",fg+:${IG_COLOR_WHITE:-#c0caf5}"
  fzf_colors+=",hl:${IG_COLOR_GREEN:-#73daca}"
  fzf_colors+=",info:${IG_COLOR_MAGENTA:-#bb9af7}"
  fzf_colors+=",header:${IG_COLOR_RED:-#f7768e}"

  # Welcome screen setting
  local welcome
  welcome="$(ig_config "shell.welcome" "true")"

  local generated_content="# Generated by ig-term - do not edit
export FZF_DEFAULT_OPTS=\"--color=${fzf_colors} --reverse\"
export IG_WELCOME=\"${welcome}\""

  # Write real file in IG_HOME/config/shell/, symlink to generated dir
  ig_managed_config "shell" "ig-env.sh" "${IG_CONFIG_DIR}/generated/ig-env.sh" "$generated_content"

  ig_success "Shell configured"
}

_configure_shell
